services:
  dance-dance-analytics-web:
    build: .
    container_name: dance-dance-analytics-web
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@dance-dance-analytics-db:5432/dance_db
    depends_on:
      - dance-dance-analytics-db

  dance-dance-analytics-db:
    image: postgres:15
    container_name: dance-dance-analytics-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dance_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
