services:
  dance-dance-analytics-web:
    build: .
    container_name: dance-dance-analytics-web
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - dance-dance-analytics-db
    networks:
      - default

  dance-dance-analytics-db:
    image: postgres:15
    container_name: dance-dance-analytics-db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default

volumes:
  postgres_data:

networks:
  default:
