version: "3.9"

services:
  dance-dance-analytics-web:
    build: .
    container_name: dance-dance-analytics-web
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - dance-dance-analytics-db

  dance-dance-analytics-db:
    image: postgres:15
    container_name: dance-dance-analytics-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: dance_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
