"""initial

Revision ID: 8f1b286abecf
Revises: 
Create Date: 2025-06-01 18:57:28.352054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f1b286abecf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banner_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('blob', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simfile_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_table('mix_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('system', sa.Text(), nullable=False),
    sa.Column('region', sa.Text(), nullable=False),
    sa.Column('release', sa.Date(), nullable=False),
    sa.Column('banner_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['banner_id'], ['banner_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('banner_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('song_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mix_id', sa.Uuid(), nullable=False),
    sa.Column('banner_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('artist', sa.Text(), nullable=True),
    sa.Column('title_translit', sa.Text(), nullable=True),
    sa.Column('artist_translit', sa.Text(), nullable=True),
    sa.Column('samplestart', sa.Float(), nullable=True),
    sa.Column('samplelength', sa.Float(), nullable=True),
    sa.Column('displaybpm', sa.Text(), nullable=True),
    sa.Column('stops', sa.Text(), nullable=True),
    sa.Column('bpms', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['banner_id'], ['banner_records.id'], ),
    sa.ForeignKeyConstraint(['id'], ['simfile_records.id'], ),
    sa.ForeignKeyConstraint(['mix_id'], ['mix_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('banner_id')
    )
    op.create_table('chart_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('song_id', sa.Uuid(), nullable=False),
    sa.Column('stepstype', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['song_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('single_chart_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('length_seconds', sa.Float(), nullable=True),
    sa.Column('display_bpm_min', sa.Float(), nullable=True),
    sa.Column('display_bpm_max', sa.Float(), nullable=True),
    sa.Column('true_bpm_min', sa.Float(), nullable=True),
    sa.Column('true_bpm_max', sa.Float(), nullable=True),
    sa.Column('bpm_changes', sa.Integer(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('jumps', sa.Integer(), nullable=True),
    sa.Column('holds', sa.Integer(), nullable=True),
    sa.Column('shock_arrows', sa.Integer(), nullable=True),
    sa.Column('hands', sa.Integer(), nullable=True),
    sa.Column('crossovers', sa.Integer(), nullable=True),
    sa.Column('footswitches', sa.Integer(), nullable=True),
    sa.Column('sideswitches', sa.Integer(), nullable=True),
    sa.Column('jacks', sa.Integer(), nullable=True),
    sa.Column('brackets', sa.Integer(), nullable=True),
    sa.Column('total_stream', sa.Integer(), nullable=True),
    sa.Column('max_nps', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['chart_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('single_chart_records')
    op.drop_table('chart_records')
    op.drop_table('song_records')
    op.drop_table('mix_records')
    op.drop_table('simfile_records')
    op.drop_table('banner_records')
    # ### end Alembic commands ###
